#!/bin/env python

import os, sys
import traceback

FSLDIR = os.environ["FSLDIR"]
sys.path.insert(0, FSLDIR + "/lib/python")
from fabber import FabberLib, FabberException

try:
    fab = FabberLib(auto_load_models=True)

    rundata = {}
    nt = 10

    for arg in sys.argv:
        if arg.startswith("--"):
            parts = arg.split("=")
            if len(parts) == 2:
                key = parts[0][2:]
                value = parts[1]
                rundata[key] = value
            elif len(parts) == 1:
                rundata[arg[2:]] = ""

    params = {}
    model_params = fab.get_model_params(rundata)
    for key, value in rundata.items():
        if key in model_params:
            params[key] = value
            del rundata[key]

    if "nt" in rundata:
        nt = int(rundata["nt"])
        del rundata["nt"]

    print(rundata)
    print(params)
    print(nt)

    e = fab.model_evaluate(rundata, params, nt)
    print(e)
except FabberException, e:
    print e.log
    traceback.print_exc(0)
except:
    traceback.print_exc()

