# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/martinc/dev/fabber_core/pyfab/pyfab_mainwin.ui'
#
# Created: Wed Oct 12 16:21:26 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 1074)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.newBtn = QtGui.QPushButton(self.centralwidget)
        self.newBtn.setObjectName("newBtn")
        self.horizontalLayout_8.addWidget(self.newBtn)
        self.openBtn = QtGui.QPushButton(self.centralwidget)
        self.openBtn.setObjectName("openBtn")
        self.horizontalLayout_8.addWidget(self.openBtn)
        self.filenameEdit = QtGui.QLineEdit(self.centralwidget)
        self.filenameEdit.setObjectName("filenameEdit")
        self.horizontalLayout_8.addWidget(self.filenameEdit)
        self.saveBtn = QtGui.QPushButton(self.centralwidget)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_8.addWidget(self.saveBtn)
        self.saveAsBtn = QtGui.QPushButton(self.centralwidget)
        self.saveAsBtn.setObjectName("saveAsBtn")
        self.horizontalLayout_8.addWidget(self.saveAsBtn)
        self.runBtn = QtGui.QPushButton(self.centralwidget)
        self.runBtn.setObjectName("runBtn")
        self.horizontalLayout_8.addWidget(self.runBtn)
        self.runQuickBtn = QtGui.QPushButton(self.centralwidget)
        self.runQuickBtn.setObjectName("runQuickBtn")
        self.horizontalLayout_8.addWidget(self.runQuickBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.orthoFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orthoFrame.sizePolicy().hasHeightForWidth())
        self.orthoFrame.setSizePolicy(sizePolicy)
        self.orthoFrame.setMinimumSize(QtCore.QSize(600, 600))
        self.orthoFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.orthoFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.orthoFrame.setObjectName("orthoFrame")
        self.verticalLayout_9.addWidget(self.orthoFrame)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.sbX = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbX.sizePolicy().hasHeightForWidth())
        self.sbX.setSizePolicy(sizePolicy)
        self.sbX.setObjectName("sbX")
        self.horizontalLayout_5.addWidget(self.sbX)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.sbY = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbY.sizePolicy().hasHeightForWidth())
        self.sbY.setSizePolicy(sizePolicy)
        self.sbY.setObjectName("sbY")
        self.horizontalLayout_5.addWidget(self.sbY)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.sbZ = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbZ.sizePolicy().hasHeightForWidth())
        self.sbZ.setSizePolicy(sizePolicy)
        self.sbZ.setObjectName("sbZ")
        self.horizontalLayout_5.addWidget(self.sbZ)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.sbT = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbT.sizePolicy().hasHeightForWidth())
        self.sbT.setSizePolicy(sizePolicy)
        self.sbT.setObjectName("sbT")
        self.horizontalLayout_5.addWidget(self.sbT)
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_5.addWidget(self.label_19)
        self.dataValueEdit = QtGui.QLineEdit(self.centralwidget)
        self.dataValueEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dataValueEdit.setObjectName("dataValueEdit")
        self.horizontalLayout_5.addWidget(self.dataValueEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.timeSlider = QtGui.QSlider(self.centralwidget)
        self.timeSlider.setMinimumSize(QtCore.QSize(0, 10))
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.horizontalLayout_7.addWidget(self.timeSlider)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_12.addWidget(self.label)
        self.currentEdit = QtGui.QLineEdit(self.centralwidget)
        self.currentEdit.setObjectName("currentEdit")
        self.horizontalLayout_12.addWidget(self.currentEdit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.visibleCB = QtGui.QCheckBox(self.centralwidget)
        self.visibleCB.setText("")
        self.visibleCB.setObjectName("visibleCB")
        self.horizontalLayout_6.addWidget(self.visibleCB)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.alphaSlider = QtGui.QSlider(self.centralwidget)
        self.alphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSlider.setObjectName("alphaSlider")
        self.horizontalLayout_6.addWidget(self.alphaSlider)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_6.addWidget(self.label_16)
        self.cmCombo = QtGui.QComboBox(self.centralwidget)
        self.cmCombo.setObjectName("cmCombo")
        self.horizontalLayout_6.addWidget(self.cmCombo)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_10.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.fitFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitFrame.sizePolicy().hasHeightForWidth())
        self.fitFrame.setSizePolicy(sizePolicy)
        self.fitFrame.setMinimumSize(QtCore.QSize(400, 400))
        self.fitFrame.setMaximumSize(QtCore.QSize(400, 400))
        self.fitFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fitFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.fitFrame.setObjectName("fitFrame")
        self.verticalLayout.addWidget(self.fitFrame)
        self.paramTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramTable.sizePolicy().hasHeightForWidth())
        self.paramTable.setSizePolicy(sizePolicy)
        self.paramTable.setMaximumSize(QtCore.QSize(400, 16777215))
        self.paramTable.setColumnCount(3)
        self.paramTable.setObjectName("paramTable")
        self.paramTable.setColumnCount(3)
        self.paramTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.paramTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.paramTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.paramTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.paramTable)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_16.addWidget(self.label_3)
        self.dataModeCombo = QtGui.QComboBox(self.centralwidget)
        self.dataModeCombo.setObjectName("dataModeCombo")
        self.dataModeCombo.addItem("")
        self.dataModeCombo.addItem("")
        self.horizontalLayout_16.addWidget(self.dataModeCombo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.inputFilesTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFilesTable.sizePolicy().hasHeightForWidth())
        self.inputFilesTable.setSizePolicy(sizePolicy)
        self.inputFilesTable.setMinimumSize(QtCore.QSize(50, 100))
        self.inputFilesTable.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.inputFilesTable.setFont(font)
        self.inputFilesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.inputFilesTable.setColumnCount(1)
        self.inputFilesTable.setObjectName("inputFilesTable")
        self.inputFilesTable.setColumnCount(1)
        self.inputFilesTable.setRowCount(0)
        self.inputFilesTable.horizontalHeader().setVisible(False)
        self.inputFilesTable.horizontalHeader().setStretchLastSection(True)
        self.inputFilesTable.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.inputFilesTable)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.maskBtn = QtGui.QPushButton(self.centralwidget)
        self.maskBtn.setObjectName("maskBtn")
        self.horizontalLayout_4.addWidget(self.maskBtn)
        self.dataBtn = QtGui.QPushButton(self.centralwidget)
        self.dataBtn.setObjectName("dataBtn")
        self.horizontalLayout_4.addWidget(self.dataBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.dateLabel = QtGui.QLabel(self.centralwidget)
        self.dateLabel.setObjectName("dateLabel")
        self.horizontalLayout_11.addWidget(self.dateLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.outputFilesTable = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputFilesTable.sizePolicy().hasHeightForWidth())
        self.outputFilesTable.setSizePolicy(sizePolicy)
        self.outputFilesTable.setMinimumSize(QtCore.QSize(50, 100))
        self.outputFilesTable.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.outputFilesTable.setFont(font)
        self.outputFilesTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.outputFilesTable.setColumnCount(1)
        self.outputFilesTable.setObjectName("outputFilesTable")
        self.outputFilesTable.setColumnCount(1)
        self.outputFilesTable.setRowCount(0)
        self.outputFilesTable.horizontalHeader().setVisible(False)
        self.outputFilesTable.horizontalHeader().setStretchLastSection(True)
        self.outputFilesTable.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.outputFilesTable)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.showLogBtn = QtGui.QPushButton(self.centralwidget)
        self.showLogBtn.setObjectName("showLogBtn")
        self.horizontalLayout_3.addWidget(self.showLogBtn)
        self.chooseRunBtn = QtGui.QPushButton(self.centralwidget)
        self.chooseRunBtn.setObjectName("chooseRunBtn")
        self.horizontalLayout_3.addWidget(self.chooseRunBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.modelCombo = QtGui.QComboBox(self.centralwidget)
        self.modelCombo.setObjectName("modelCombo")
        self.gridLayout_2.addWidget(self.modelCombo, 2, 1, 1, 1)
        self.methodCombo = QtGui.QComboBox(self.centralwidget)
        self.methodCombo.setObjectName("methodCombo")
        self.gridLayout_2.addWidget(self.methodCombo, 4, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 5, 1, 1, 1)
        self.generalOptionsBtn = QtGui.QPushButton(self.centralwidget)
        self.generalOptionsBtn.setObjectName("generalOptionsBtn")
        self.gridLayout_2.addWidget(self.generalOptionsBtn, 5, 2, 1, 1)
        self.methodOptionsBtn = QtGui.QPushButton(self.centralwidget)
        self.methodOptionsBtn.setObjectName("methodOptionsBtn")
        self.gridLayout_2.addWidget(self.methodOptionsBtn, 4, 2, 1, 1)
        self.modelOptionsBtn = QtGui.QPushButton(self.centralwidget)
        self.modelOptionsBtn.setObjectName("modelOptionsBtn")
        self.gridLayout_2.addWidget(self.modelOptionsBtn, 2, 2, 1, 1)
        self.execChangeBtn = QtGui.QPushButton(self.centralwidget)
        self.execChangeBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.execChangeBtn.setObjectName("execChangeBtn")
        self.gridLayout_2.addWidget(self.execChangeBtn, 0, 2, 1, 1)
        self.execEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execEdit.sizePolicy().hasHeightForWidth())
        self.execEdit.setSizePolicy(sizePolicy)
        self.execEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.execEdit.setObjectName("execEdit")
        self.gridLayout_2.addWidget(self.execEdit, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        self.horizontalLayout_15.addLayout(self.verticalLayout_11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.newBtn.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.openBtn.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBtn.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsBtn.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.runBtn.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.runQuickBtn.setText(QtGui.QApplication.translate("MainWindow", "Quick Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Selected File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Visible", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Colour table", None, QtGui.QApplication.UnicodeUTF8))
        self.paramTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.paramTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Mean", None, QtGui.QApplication.UnicodeUTF8))
        self.paramTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Std.dev", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Input Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Data mode", None, QtGui.QApplication.UnicodeUTF8))
        self.dataModeCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.dataModeCombo.setItemText(1, QtGui.QApplication.translate("MainWindow", "Multiple", None, QtGui.QApplication.UnicodeUTF8))
        self.maskBtn.setText(QtGui.QApplication.translate("MainWindow", "Load Mask", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBtn.setText(QtGui.QApplication.translate("MainWindow", "Load Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Output Data", None, QtGui.QApplication.UnicodeUTF8))
        self.dateLabel.setText(QtGui.QApplication.translate("MainWindow", "Run date", None, QtGui.QApplication.UnicodeUTF8))
        self.showLogBtn.setText(QtGui.QApplication.translate("MainWindow", "Show logfile", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseRunBtn.setText(QtGui.QApplication.translate("MainWindow", "Choose Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Fabber Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Forward model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Inference method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Executable", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "General options", None, QtGui.QApplication.UnicodeUTF8))
        self.generalOptionsBtn.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.methodOptionsBtn.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.modelOptionsBtn.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.execChangeBtn.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/martinc/dev/fabber_core/pyfab/pyfab_optdialog.ui'
#
# Created: Wed Oct 12 16:21:26 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ModelOptionsDialog(object):
    def setupUi(self, ModelOptionsDialog):
        ModelOptionsDialog.setObjectName("ModelOptionsDialog")
        ModelOptionsDialog.resize(417, 308)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ModelOptionsDialog.sizePolicy().hasHeightForWidth())
        ModelOptionsDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(ModelOptionsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.modelLabel = QtGui.QLabel(ModelOptionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelLabel.sizePolicy().hasHeightForWidth())
        self.modelLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.modelLabel.setFont(font)
        self.modelLabel.setObjectName("modelLabel")
        self.verticalLayout.addWidget(self.modelLabel)
        self.descLabel = QtGui.QLabel(ModelOptionsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descLabel.sizePolicy().hasHeightForWidth())
        self.descLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.descLabel.setFont(font)
        self.descLabel.setObjectName("descLabel")
        self.verticalLayout.addWidget(self.descLabel)
        self.grid = QtGui.QGridLayout()
        self.grid.setObjectName("grid")
        self.verticalLayout.addLayout(self.grid)
        self.buttonBox = QtGui.QDialogButtonBox(ModelOptionsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ModelOptionsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ModelOptionsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ModelOptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ModelOptionsDialog)

    def retranslateUi(self, ModelOptionsDialog):
        ModelOptionsDialog.setWindowTitle(QtGui.QApplication.translate("ModelOptionsDialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.modelLabel.setText(QtGui.QApplication.translate("ModelOptionsDialog", "Model", None, QtGui.QApplication.UnicodeUTF8))
        self.descLabel.setText(QtGui.QApplication.translate("ModelOptionsDialog", "Description", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/martinc/dev/fabber_core/pyfab/pyfab_logview.ui'
#
# Created: Wed Oct 12 16:21:27 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LogViewer(object):
    def setupUi(self, LogViewer):
        LogViewer.setObjectName("LogViewer")
        LogViewer.resize(600, 488)
        LogViewer.setMinimumSize(QtCore.QSize(600, 0))
        self.verticalLayout = QtGui.QVBoxLayout(LogViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtGui.QTextBrowser(LogViewer)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.buttonBox = QtGui.QDialogButtonBox(LogViewer)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LogViewer)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), LogViewer.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), LogViewer.reject)
        QtCore.QMetaObject.connectSlotsByName(LogViewer)

    def retranslateUi(self, LogViewer):
        LogViewer.setWindowTitle(QtGui.QApplication.translate("LogViewer", "Dialog", None, QtGui.QApplication.UnicodeUTF8))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/martinc/dev/fabber_core/pyfab/pyfab_chooserun.ui'
#
# Created: Wed Oct 12 16:21:27 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ChooseRunDialog(object):
    def setupUi(self, ChooseRunDialog):
        ChooseRunDialog.setObjectName("ChooseRunDialog")
        ChooseRunDialog.resize(526, 453)
        ChooseRunDialog.setModal(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ChooseRunDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(ChooseRunDialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.table = QtGui.QTableWidget(ChooseRunDialog)
        self.table.setColumnCount(2)
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.table)
        self.buttonBox = QtGui.QDialogButtonBox(ChooseRunDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(ChooseRunDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ChooseRunDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ChooseRunDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ChooseRunDialog)

    def retranslateUi(self, ChooseRunDialog):
        ChooseRunDialog.setWindowTitle(QtGui.QApplication.translate("ChooseRunDialog", "Choose Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ChooseRunDialog", "The following runs were detected for the current output directory", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ChooseRunDialog", "Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ChooseRunDialog", "Timestamp", None, QtGui.QApplication.UnicodeUTF8))

